### ISSUE TITLE
[🐛]: Right-click events desync on dedicated server

### ISSUE THREAD

**Issue by sentientyeet** [TerraFirmaGreg-Team/Modpack-Modern#1855]
### Was this bug reported before?

- [x] No, it was not.

### Version modpack used

0.10.14

### Environment

Forge Server

### New Worlds

Unsure

### Please provide a link to your latest.log, if relevant.

https://mclo.gs/emeYPPE

### Expected Behavior

Player A right clicks tile entity e.g. create vacuum chamber or done soup above a campfire in a pot
Player B observes that the block state changed e.g. vacuum chamber switched pressure/vacuum mode or soup amount in pot lowered by N

### Actual Behavior

Player A right clicks tile entity e.g. create vacuum chamber or done soup above a campfire in a pot
Player B observes that the block state _has not changed_ e.g. vacuum chamber has not switched pressure/vacuum mode or soup amount in pot has not lowered by N

### Steps to Reproduce

Player A right clicks a tile entity that would change its state
Player B observes

**Comment by Pyritie** [comment]
works fine here, this sounds like something wrong with specifically your server because none of our other server players are reporting this issue

**Comment by D3nnis3n** [comment]
We actually have the same issue with the modpack, just didn't bother to report - things like making a canoe, other people on the server can't see the same changes when carving out the log until a reconnect.

Similarly, in the anvil despite taking out the bars, other players can still see it until the player puts new stuff in or the others reconnect. Pretty frequent problem.

**Comment by sentientyeet** [comment]
> We actually have the same issue with the modpack, just didn't bother to report - things like making a canoe, other people on the server can't see the same changes when carving out the log until a reconnect.
> 
> Similarly, in the anvil despite taking out the bars, other players can still see it until the player puts new stuff in or the others reconnect. Pretty frequent problem.

yep exactly as you're describing;

**Comment by Redeix** [comment]
sounds like packets data packets are getting stuck somewhere along the way. Which could happen for a million different reasons including your individual connections to the server. If they are only happening to TFC events I would report it to them not us.

**Comment by D3nnis3n** [comment]
I doubt it's on TFC side, the issue does not appear on our custom TFC server that only has TFC and some of the addons for it:

<img width="404" height="741" alt="Image" src="https://github.com/user-attachments/assets/1ff9bb7f-7886-4752-856e-f912667e7cc5" />

(We host multiple MC servers with different, mostly custom modpacks, this is the first time we try a premade one)

Both servers use identical network settings and are on the same host system, so those can be excluded as well. Likely a mod interaction issue in the pack.

If it affects other stuff than TFC, I don't know - we have only just reached Black Steel. I can report when we get further.

**Comment by sentientyeet** [comment]
i'm running the server via docker, maybe something network related happening there, which is odd considering I've run other packs this way and it was fine (both pre-made and self done)

**Comment by D3nnis3n** [comment]
We don't use docker, running directly on dedicated machine.

**Comment by ByteAnnyTA** [comment]
I can confirm that this is happening still in 0.11.27.
- The dugout canoe progress does not update for the players not involved in the steps
- Most critically, the stability cave-in tooltips do not update either if another player is the one to place the supports, making mining together into a slog. They update upon a relog or if the chunk is newly loaded.

Dedicated server, Debian, non-default port for the server (maybe this is the crux of the issue?). Not Docker.

**Comment by Pyritie** [comment]
the dugout canoe should be reported to firmaciv, not here, while the collapse tooltip should be fixed in 0.11.27

**Comment by D3nnis3n** [comment]
Both still the case for us on 0.11.27 as well, so not fixed. (Though given this was closed, we didn't bother reporting anymore)

**Comment by SakuraKitsurugi** [comment]
@D3nnis3n Did you start your server at 0.11.27 or did you update to it? If you updated it - did you fully reinstall it or did you just change the files?

**Comment by Pyritie** [comment]
can you open a new issue for the collapse thing then please, after
confirming it's still present on a reinstall? we've been optimizing the
collapse checks recently and this is probably a side effect of that

**Comment by ByteAnnyTA** [comment]
I can also confirm that both of them are still current issues in 0.11.27 for us. The server was a fresh install of 0.11.27.

**Comment by Pyritie** [comment]
ok, then open a new issue for the collapse tooltips then please

**Comment by D3nnis3n** [comment]
> [@D3nnis3n](https://github.com/D3nnis3n) Did you start your server at 0.11.27 or did you update to it? If you updated it - did you fully reinstall it or did you just change the files?

Update. We update by removing the whole configs, defaultconfigs, tacz and mods folders, then copy the new ones in and add our tfc-server.toml and BlueMap and its configs on top.

**Comment by Mqrius** [comment]
Right I think that's all of them.

Soup in a pot over a campfire doesn't change fluid level for either player. You're thinking of jam from a pot, where the level _does_ change. (Edit: I haven't checked but I think jam does sync)
